services:
  loki:
    container_name: loki
    image: docker.arvancloud.ir/grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_central
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 600M
    logging:
      options:
        max-size: "1024m"

  grafana:
    image: docker.arvancloud.ir/grafana/grafana-oss:10.3.1
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # - GF_LOG_LEVEL=warn
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    # volumes:
      # - grafana:/var/lib/grafana
    networks:
      - internal_central
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 600M
    logging:
      options:
        max-size: "1024m"

  vector_central:
    image: docker.arvancloud.ir/timberio/vector:0.35.0-alpine
    container_name: vector_central
    ports:
      - "5123:5123/udp"
    volumes:
      - ./config/vector/vector.central.yaml:/etc/vector/vector.yaml:ro
    networks:
      - internal_central
      - vector_central
    depends_on:
      loki:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 600M
    logging:
      options:
        max-size: "1024m"

# volumes:
#   grafana:

networks:
  internal_central:
  vector_central:
    name: vector_central
