services:
  vector:
    image: timberio/vector:0.35.0-alpine
    container_name: vector
    restart: always
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
