api:
  enabled: false

sources:
  vectorـagent:
    type: vector
    address: 192.168.16.2:5124

sinks:
  loki:
    type: loki
    endpoint: 'http://loki:3100'
    healthcheck:
      enabled: false
    inputs: ["vectorـagent"]
    encoding:
      codec: json
    labels:
      logsource: vector_internal_container

  # console:
  #   type: console
  #   target: stdout
  #   inputs:
  #     - vector
  #   encoding:
  #     codec: json
